AWSTemplateFormatVersion: '2010-09-09'
Description: Template CloudFormation - EC2 básica (t2.micro)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome do par de chaves para acessar via SSH
  MyIP:
    Type: String
    Description: Seu IP público com /32 (exemplo: 1.2.3.4/32)

Mappings:
  RegionMap:
    sa-east-1:
      AMI: ami-04c3372b1efc4f6c5   # Amazon Linux 2 - São Paulo
    us-east-1:
      AMI: ami-0e2c8caa4b6378d8c   # Amazon Linux 2 - Virgínia

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH apenas do meu IP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: [!Ref SecurityGroup]
          SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: EC2-Basica

Outputs:
  InstancePublicIP:
    Description: IP público da instância criada
    Value: !GetAtt Instance.PublicIp
